In [1]:
from dtaidistance import dtw
from dtaidistance import dtw_visualisation as dtwvis
import numpy as np

TypeError: plot_warping() missing 2 required positional arguments: 's2' and 'path'

In [2]:
X = np.load('electricity/data/electricity.npy')

In [3]:
ds = dtw.distance_matrix_fast(X[:,-10:])

In [4]:
ds


array([[           inf, 3.01375352e+02, 4.80173207e+00, ...,
        1.59685234e+03, 9.62413417e+03, 9.42208303e+04],
       [           inf,            inf, 2.97837741e+02, ...,
        1.32847803e+03, 9.32380897e+03, 9.39203959e+04],
       [           inf,            inf,            inf, ...,
        1.59439468e+03, 9.62081525e+03, 9.42175868e+04],
       ...,
       [           inf,            inf,            inf, ...,
                   inf, 8.15722517e+03, 9.27430697e+04],
       [           inf,            inf,            inf, ...,
                   inf,            inf, 8.46110028e+04],
       [           inf,            inf,            inf, ...,
                   inf,            inf,            inf]])

In [5]:
from dtaidistance import dtw
import numpy as np
series = np.matrix([
    [0.0, 0, 1, 2, 1, 0, 1, 0, 0],
    [0.0, 1, 2, 0, 0, 0, 0, 0, 0],
    [0.0, 0, 1, 2, 1, 0, 0, 0, 0]])
ds = dtw.distance_matrix_fast(series)

In [6]:
ds

array([[       inf, 1.41421356, 1.        ],
       [       inf,        inf, 1.        ],
       [       inf,        inf,        inf]])

In [7]:
from dtaidistance import clustering
# Custom Hierarchical clustering
model1 = clustering.Hierarchical(dtw.distance_matrix_fast, {})
cluster_idx = model1.fit(series)
# Augment Hierarchical object to keep track of the full tree
model2 = clustering.HierarchicalTree(model1)
cluster_idx = model2.fit(series)
# SciPy linkage clustering
model3 = clustering.LinkageTree(dtw.distance_matrix_fast, {})
cluster_idx = model3.fit(series)

 67%|██████▋   | 2/3 [00:00<00:00, 999.48it/s]


In [8]:
model2.plot("myplot.png")

(None, None)

In [9]:
np.random.rand(8,5)

array([[0.63381948, 0.85437294, 0.94973673, 0.23738747, 0.67074602],
       [0.14510989, 0.58884947, 0.70850912, 0.26236543, 0.84803009],
       [0.02962946, 0.93208003, 0.52516888, 0.7900869 , 0.00864912],
       [0.74250298, 0.28334578, 0.14979974, 0.79390265, 0.74841514],
       [0.68258473, 0.44861757, 0.89039922, 0.18444561, 0.41117311],
       [0.12429782, 0.88222288, 0.01409517, 0.56642211, 0.9998787 ],
       [0.82082253, 0.87666574, 0.63067244, 0.58104776, 0.49237673],
       [0.44928359, 0.04235218, 0.8791988 , 0.42963211, 0.16928054]])

In [10]:
from dtaidistance import dtw
import numpy as np
import time
t = time.time()
series = np.random.rand(400,2000)
ds = dtw.distance_matrix_fast(series)
print(f"{time.time() - t:.2f}")
ds

506.62


array([[       inf, 7.82483448, 7.8589656 , ..., 7.78714178, 7.78213574,
        7.82102887],
       [       inf,        inf, 7.70918417, ..., 7.71190693, 7.75963127,
        7.78115104],
       [       inf,        inf,        inf, ..., 7.66744321, 7.71416744,
        7.75603576],
       ...,
       [       inf,        inf,        inf, ...,        inf, 7.83143579,
        7.76728672],
       [       inf,        inf,        inf, ...,        inf,        inf,
        7.86287046],
       [       inf,        inf,        inf, ...,        inf,        inf,
               inf]])

In [11]:
ds[np.isinf(ds)] = 0

In [12]:
ds = ds + ds.T

In [13]:
ds + ds.T

array([[ 0.        , 15.64966896, 15.7179312 , ..., 15.57428356,
        15.56427148, 15.64205774],
       [15.64966896,  0.        , 15.41836834, ..., 15.42381386,
        15.51926253, 15.56230209],
       [15.7179312 , 15.41836834,  0.        , ..., 15.33488643,
        15.42833488, 15.51207152],
       ...,
       [15.57428356, 15.42381386, 15.33488643, ...,  0.        ,
        15.66287158, 15.53457343],
       [15.56427148, 15.51926253, 15.42833488, ..., 15.66287158,
         0.        , 15.72574093],
       [15.64205774, 15.56230209, 15.51207152, ..., 15.53457343,
        15.72574093,  0.        ]])

In [14]:

from sklearn.metrics import pairwise_distances
X = np.random.rand(5,5)
pairwise_distances(X, metric='euclidean')

array([[0.        , 0.85264022, 0.40660886, 0.90936533, 0.96889267],
       [0.85264022, 0.        , 0.75517905, 0.69138056, 0.99859354],
       [0.40660886, 0.75517905, 0.        , 1.05347829, 1.11044783],
       [0.90936533, 0.69138056, 1.05347829, 0.        , 0.98598828],
       [0.96889267, 0.99859354, 1.11044783, 0.98598828, 0.        ]])